version: 2.1

executors:
  python-selenium-grid:
    docker:
      # Primary container for Python tests
      - image: cimg/python:3.11
        environment:
          PIP_CACHE_DIR: ~/.cache/pip
      # Selenium Hub (latest)
      - image: selenium/hub:latest
        name: selenium-hub
        environment:
          GRID_MAX_SESSION: 5
      # Chrome Node (latest)
      - image: selenium/node-chrome:latest
        environment:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
          SE_NODE_MAX_SESSIONS: 2
          SE_NODE_PORT: 5555
      # Firefox Node (latest)
      - image: selenium/node-firefox:latest
        environment:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
          SE_NODE_MAX_SESSIONS: 2
          SE_NODE_PORT: 5556

jobs:
  test:
    executor: python-selenium-grid
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install selenium pytest
      - run:
          name: Run Selenium tests
          command: |
            . venv/bin/activate
            pytest test_google.py --maxfail=1 --disable-warnings
